### PR TITLE
DOC: README.md: let g:unite_source_menu_menus={ }

### PR DESCRIPTION
**Pull request by westurner**
Without this, the error is:

```
E121: Undefined variable: g:unite_source_menu_menus
```

### CODE REVIEW

**Comment by wsdjeg** [comment]
I think it is useage of viml ,not unite.
if you want to set
`let g:unite_source_menu_menus.Test  = "something"`
that means you are set the value of the key `Test` in dict g:unite_source_menu_menus,so you must define g:unite_source_menu_menus.

**Comment by wsdjeg** [comment]
and you should not use 
`let g:unite_source_menu_menus = {}`
it will change the value if it exist.
`let g:unite_source_menu_menus =get(g:,'unite_source_menu_menus',{})`  will be better

**Comment by westurner** [comment]
Thanks!

``let g:unite_source_menu_menus =get(g:,'unite_source_menu_menus',{})``

**Comment by Shougo** [comment]
LGTM

**Pull request merged**
